version: 2.0
jobs:
  build_gcc_latest:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: sudo apt-get install cmake
      - run: sudo add-apt-repository ppa:chrome/magnum.graphics
      - run: sudo apt-get update
      - run: sudo apt-get install magnum magnum-dev

      - run: mkdir -p build && cd build
      - run: cmake -DCMAKE_BUILD_TYPE=Release .. 

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_latest
