version: 2.0
jobs:
  build_gcc_latest:
    docker:
      - image: kghose/liftoff:latest
    steps:
      - checkout
      - run: cd /root/project && mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && make

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_latest
