FROM    ubuntu:bionic
LABEL   maintainer="kghose"
LABEL   description="gcc, cmake, magnum/corrade"

# For add-apt-repository
RUN apt-get update && apt-get install -y \
    software-properties-common \
    cmake \
    git \
    curl \
    wget

# For Magnum
RUN add-apt-repository -y ppa:chrome/magnum.graphics
RUN apt-get update && apt-get install -y magnum magnum-dev

# For gcc
RUN add-apt-repository -y ppa:ubuntu-toolchain-r/test
RUN apt-get update && apt-get install -y gcc-8 g++-8 gcc-8
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100 \
    && update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-8 100


# docker build -f dockerfile -t kghose/liftoff .
# docker push kghose/liftoff

# You can do local test compiles by
# docker run -ti --mount type=bind,source=/Users/kghose/Code/groho,target=/root/groho kghose/liftoff