@startuml startup

:Scenario changed>
:Read Scenario file;
:Load nearest valid checkpoint;
note right
  This is the heart of work reuse and is
  how we can make iterative development
  of trajectories more responsive.
end note

:Truncate history\nand checkpoint files;
note right
  This detail is noted because it is easy 
  to overlook, and can be complicated to 
  implement.
end note
:Create new Simulation;
:Restart Simulator;

stop

@enduml

@startuml simulatorloop

:start simulation>
:warmup engine if needed;
note right
  If we have a cold start (not from a checkpoint)
  we need to run for three steps or more to set
  vel and acc for all bodies. Flightplan actions 
  often need vel and acc of bodies for their
  computations. 
end note

repeat 

:set orrery pos;
:compute accel from gravity;
:compute accel from flight plans;
:update spacecraft position;
:serialize data;

repeat while (interrupted?) is (no)
->yes;
stop

@enduml

@startuml serialize

start 

repeat

fork
repeat

  if (stop?) then (yes)
    break;
  else (no)

    if (sample?) then (yes)
      :write buf (b);
    else (no)
    endif

    if (checkpoint?) then (yes)
      :write checkpoint;
    else (no)
    endif


  endif

repeat while(full?) is (no)

fork again
partition Save #GreenYellow{
  if (data?) then (yes)
    :save buf (1 - b);
  else (no)
  endif

  if (stop?) then (yes)
    :quit = true;
  else (no)
  endif
}
end fork

:b = 1 - b\n(switch buffer);

repeat while (quit?) is (no)

stop
@enduml
