@startuml Sequence

actor User
participant "Scenario file" as scnf
participant Simulator
participant Simulation

participant "Plotting file" as plotf
participant Plotter
collections Plot

Simulator -> scnf: Load scenario
scnf --> Simulator: scenario
Simulator -> Simulation: restart
activate Simulation

Simulator -> scnf: Changed?
scnf --> Simulator: No


Plotter -> plotf: Changed?
Plotter <-- plotf: No

User --> scnf: edit


Plotter -> Simulation: Fresh Data?
Plotter <-- Simulation: Data
Plotter -> Plot: Update


User --> plotf: edit
Plotter -> plotf: Changed?
Plotter <-- plotf: plot info
Plotter -> Simulation: Fetch data
Simulation --> Plotter: Data
Plotter -> Plot: Update

Simulator -> scnf: Changed?
scnf --> Simulator: scenario

Simulator -> Simulation: stop
deactivate Simulation


Plotter -> Simulation: Fresh Data?
Plotter <- Simulation: Restarting


Simulator -> Simulation: restart
activate Simulation


Plotter -> Simulation: Fresh Data?
Plotter <-- Simulation: Data
Plotter -> Plot: Update

Simulator -> Simulation: done
deactivate Simulation

Plotter -> Simulation: Fresh Data?
Plotter <-- Simulation: Data
Plotter -> Plot: Update


Plotter -> Simulation: Fresh Data?
Plotter <-- Simulation: No


User --> plotf: edit
Plotter -> plotf: Changed?
Plotter <-- plotf: plot info
Plotter -> Simulation: Fetch data
Plotter <-- Simulation: Data
Plotter -> Plot: Update

@enduml