@startuml simulator

|#GreenYellow|Checkpoint File|

|#Gray|Event File|

|#Cyan|Trajectory File|

|Simulation|

start

:restart(scenario)>

while (scenario_changed?) is (yes)
  :checkpoint_from(scenario);
  :state_from_checkpoint(checkpoint);
  repeat
    :advance_simulation(state);

    |Simulation|
    split
      |Checkpoint File|
      if (save checkpoint?) then (yes)
        :save_checkpoint(pos_data);
      else (no)
      endif
      :...;
      detach

    split again
      |Event File|
      if (event?) then (yes)
        :write(event);
      else (no)
      endif
      :...;
      detach

    split again
      |Trajectory File|
      if (sample?) then (yes)
        :transform_coordinates(pos_data);
        :compress(pos_data);
        :save(pos_data);
      else (no)
      endif
      :...;
      detach

    end split 

  |Simulation|
  repeat while (interrupted? or done?) is (no)
  -> yes;
  
endwhile (no)
stop

@enduml
