@startuml usecases

User -> (Create scenario)
(Create scenario) <|-- (Change scenario)

User --> (Visualize simulation)
(Visualize simulation) <|-- (Add sub-views)

User --> (Print visualization)

@enduml