name: sim-groho

on: [push]

jobs:
  tests:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        cd tests && mkdir build && cd build
        cmake .. 
        make
    - name: run tests
      run: cd tests && ./build/tests -s
