name: Tests

on: [push]

jobs:
  tests:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: 'true'
    - name: build tests and run
      run: |
        cd tests
        mkdir build && cd build
        cmake ..
        make
        cd ../
        ./build/tests -s
